In [162]:
import numpy as np

In [164]:
np.__version__

'1.26.4'

In [166]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# Creating list

In [169]:
my_list = [0,1,2,3,4,5]
my_list 

[0, 1, 2, 3, 4, 5]

In [171]:
type(my_list)

list

In [172]:
arr = np.array(my_list)

In [175]:
arr

array([0, 1, 2, 3, 4, 5])

In [176]:
type(arr)

numpy.ndarray

In [177]:
type(my_list)

list

In [180]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [182]:
np.arange(3.0)

array([0., 1., 2.])

In [183]:
np.arange(5.9)

array([0., 1., 2., 3., 4., 5.])

In [185]:
np.arange(0  , 5)

array([0, 1, 2, 3, 4])

In [187]:
np.arange(10  , 20 )

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [189]:
np.arange(20  , 10 )#1d array 

array([], dtype=int32)

In [191]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [193]:
#  1sr arg < 2nd arg

In [194]:
np.arange(-20, -10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [196]:
ar = np.arange(-20  , -10 )

In [198]:
np.arange0(0 ,10,3)

AttributeError: module 'numpy' has no attribute 'arange0'

In [ ]:
np.zeros(10)# parameter tunning


In [ ]:
np.zeros((10,30))

In [ ]:
np.random.rand(3,2)

In [ ]:
np.arange(1 , 13)

In [ ]:
np.arange(1, 13).reshape(3,4)

In [199]:
b = np.random.randint(10, 20 , (5 , 3 ))
b

array([[13, 11, 15],
       [17, 14, 17],
       [17, 16, 15],
       [11, 19, 12],
       [11, 10, 15]])

In [201]:
type(b)

numpy.ndarray

In [205]:
b

array([[13, 11, 15],
       [17, 14, 17],
       [17, 16, 15],
       [11, 19, 12],
       [11, 10, 15]])

In [207]:
b[:]

array([[13, 11, 15],
       [17, 14, 17],
       [17, 16, 15],
       [11, 19, 12],
       [11, 10, 15]])

In [209]:
b = np.random.randint(10,20,(5,4))
b

array([[19, 12, 15, 19],
       [17, 13, 11, 10],
       [10, 15, 11, 11],
       [13, 13, 11, 18],
       [14, 15, 17, 10]])

In [210]:
b[:]

array([[19, 12, 15, 19],
       [17, 13, 11, 10],
       [10, 15, 11, 11],
       [13, 13, 11, 18],
       [14, 15, 17, 10]])

In [212]:
b[1:3]

array([[17, 13, 11, 10],
       [10, 15, 11, 11]])

In [214]:
b[1,2]

11

In [215]:
b

array([[19, 12, 15, 19],
       [17, 13, 11, 10],
       [10, 15, 11, 11],
       [13, 13, 11, 18],
       [14, 15, 17, 10]])

In [218]:
b[1,3]

10

In [220]:
b[1,-1]

10

In [221]:
b[2:3]

array([[10, 15, 11, 11]])

In [224]:
b[0:-2]

array([[19, 12, 15, 19],
       [17, 13, 11, 10],
       [10, 15, 11, 11]])

In [225]:
b

array([[19, 12, 15, 19],
       [17, 13, 11, 10],
       [10, 15, 11, 11],
       [13, 13, 11, 18],
       [14, 15, 17, 10]])

In [226]:
b[0,2]

15

In [228]:
b[-5,-3]

12

In [231]:
b[-5,3]

19

In [232]:
b[-4, 2]

11

## operations 


In [237]:
a = np.random.randint(10,20,30)
a

array([14, 16, 15, 18, 11, 11, 11, 12, 14, 10, 16, 17, 15, 15, 12, 19, 14,
       10, 15, 12, 14, 13, 18, 12, 17, 11, 13, 15, 11, 11])

In [238]:
from numpy import *