# Numpy crash course

In [2]:
import numpy as np
np

<module 'numpy' from 'C:\\Users\\pratik\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

## Creating array

In [5]:
my_list = [0, 1, 2, 3, 4, 5]
my_list 

[0, 1, 2, 3, 4, 5]

In [7]:
type (my_list)

list

In [11]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(3.3)

array([0., 1., 2., 3.])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(10 , 15)

array([10, 11, 12, 13, 14])

In [21]:
np.arange(10 , 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [23]:
np.arange(-20 , 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [27]:
np.arange(-15 , -10)

array([-15, -14, -13, -12, -11])

In [29]:
np.arange(-30 , 20)

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [31]:
np.arange(10,10)

array([], dtype=int32)

In [33]:
np.arange(10, 20 , 4) # 10 - starting from , 20 - end point , 4 - step count


array([10, 14, 18])

In [35]:
np.arange(10,20 ,3,1)

TypeError: Cannot interpret '1' as a data type

## parameter tunning 

In [40]:
b1 = np.zeros(2)
b1

array([0., 0.])

In [42]:
np.zeros(5 ,dtype=int)

array([0, 0, 0, 0, 0])

In [44]:
zero = np.zeros((2,2))
zero

array([[0., 0.],
       [0., 0.]])

In [48]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [50]:
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [52]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
np.zeros((10,40))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
   

In [56]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [60]:
n = (5,7)
n1=(6,8)
print(np.zeros(n))
print(np.zeros(n1))


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [62]:
print(np.zeros(n1))



[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [64]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

## add new notebook and compare np and *

In [79]:
from numpy import*
arange(3)

array([0, 1, 2])

In [81]:
zeros(5)

array([0., 0., 0., 0., 0.])

In [85]:
range(12)
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [89]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [93]:
from numpy import*
zeros(5)

array([0., 0., 0., 0., 0.])

In [95]:
np.random.rand(4) # array display in float

array([0.13988266, 0.51316132, 0.72274134, 0.28746238])

In [104]:
np.random.randint(4)# by adding int shows value


0

In [110]:
np.random.randint(2,20)

4

In [117]:
np.random.randint(1,10,4)


array([7, 3, 2, 8])

In [119]:
np.random.randint(1,10,4)

array([9, 4, 9, 8])

In [123]:
np.random.randint(10,21,3)

array([14, 13, 20])

In [127]:
np.random.randint(10,40,(10,10)) # it will generate elements 10 - 30 with 4*4 matrix

array([[11, 11, 14, 23, 28, 10, 15, 30, 36, 29],
       [27, 22, 11, 16, 34, 37, 29, 31, 26, 12],
       [32, 13, 33, 36, 32, 14, 22, 18, 19, 33],
       [28, 36, 35, 12, 26, 33, 19, 27, 27, 32],
       [39, 16, 10, 26, 38, 37, 39, 11, 32, 26],
       [39, 34, 32, 20, 33, 35, 30, 25, 25, 11],
       [32, 26, 27, 12, 26, 25, 34, 29, 17, 14],
       [19, 12, 24, 33, 36, 23, 15, 37, 16, 11],
       [29, 30, 14, 33, 12, 25, 29, 24, 21, 24],
       [15, 18, 14, 14, 33, 24, 22, 25, 33, 36]])

In [141]:
b = np.random.randint(10,20,(6,4))
b

array([[11, 14, 14, 12],
       [18, 12, 13, 17],
       [13, 17, 13, 12],
       [15, 18, 11, 15],
       [15, 10, 11, 10],
       [13, 19, 11, 14]])

In [143]:
b[:]

array([[11, 14, 14, 12],
       [18, 12, 13, 17],
       [13, 17, 13, 12],
       [15, 18, 11, 15],
       [15, 10, 11, 10],
       [13, 19, 11, 14]])

In [145]:
b[0:2]


array([[11, 14, 14, 12],
       [18, 12, 13, 17]])

In [147]:
b[0:-1]

array([[11, 14, 14, 12],
       [18, 12, 13, 17],
       [13, 17, 13, 12],
       [15, 18, 11, 15],
       [15, 10, 11, 10]])

In [151]:
np.random.randint(10,20,(5,5))

array([[15, 10, 11, 18, 17],
       [10, 18, 17, 12, 15],
       [10, 18, 13, 10, 16],
       [17, 15, 15, 17, 15],
       [15, 19, 17, 16, 13]])

## operation 

In [168]:
a = np.random.randint(10,20,3)
a

array([19, 10, 19])

NameError: name 'arr' is not defined